### ISSUE TITLE
log-warning - roadtraffic.0.test.route.refresh is invalid

### ISSUE THREAD

**Issue by fabiankrauss** [iobroker-community-adapters/ioBroker.roadtraffic#24]
Hello I got this Warning:

roadtraffic.0	2020-06-14 18:14:33.943	warn	(31338) This object will not be created in future versions. Please report this to the developer.
roadtraffic.0	2020-06-14 18:14:33.943	warn	(31338) Object roadtraffic.0.Arbeit Fabi.route.refresh is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
roadtraffic.0	2020-06-14 18:14:32.793	info	(31338) starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.roadtraffic, node: v12.16.3, js-controller: 3.1.4

Can you fix this? Is it a big problem?

BR
Fabian

**Comment by mcm1957** [comment]
fixed with 1.1.1
