### ISSUE TITLE
make: *** [config_deps.target.mk:13: /opt/iobroker/node_modules/cpu-features/deps/cpu_features/build/Makefile] Fehler 127

### ISSUE THREAD

**Issue by tobst96** [iobroker-community-adapters/ioBroker.roadtraffic#29]
$ iobroker add roadtraffic auto --host conbeezwei

NPM version: 6.14.13

npm install iobroker.roadtraffic@0.2.0 --loglevel error --prefix "/opt/iobroker" (System call)

/bin/sh: 1: cmake: not found

make: *** [config_deps.target.mk:13: /opt/iobroker/node_modules/cpu-features/deps/cpu_features/build/Makefile] Fehler 127

gyp ERR! build error

gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)

gyp ERR! stack at ChildProcess.emit (events.js:375:28)gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

gyp ERR! System Linux 4.19.0-18-amd64gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/cpu-featuresgyp ERR! node -v v14.17.3gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok

host.conbeezwei install adapter roadtraffic

upload [2] roadtraffic.admin /opt/iobroker/node_modules/iobroker.roadtraffic/admin/words.js words.js application/javascript

upload [1] roadtraffic.admin /opt/iobroker/node_modules/iobroker.roadtraffic/admin/roadtraffic.png roadtraffic.png image/png

upload [0] roadtraffic.admin /opt/iobroker/node_modules/iobroker.roadtraffic/admin/index_m.html index_m.html text/html

host.conbeezwei object system.adapter.roadtraffic created/updated

host.conbeezwei object _design/roadtraffic created/updated

host.conbeezwei create instance roadtraffic

host.conbeezwei object roadtraffic.0.info.connection created

host.conbeezwei object roadtraffic.0.info created

host.conbeezwei object roadtraffic.0.refresh created

host.conbeezwei object system.adapter.roadtraffic.0.logLevel created

host.conbeezwei object system.adapter.roadtraffic.0.sigKill created

host.conbeezwei object system.adapter.roadtraffic.0.eventLoopLag created

host.conbeezwei object system.adapter.roadtraffic.0.outputCount created

host.conbeezwei object system.adapter.roadtraffic.0.inputCount created

host.conbeezwei object system.adapter.roadtraffic.0.uptime created

host.conbeezwei object system.adapter.roadtraffic.0.memRss created

host.conbeezwei object system.adapter.roadtraffic.0.memHeapTotal created

host.conbeezwei object system.adapter.roadtraffic.0.memHeapUsed created

host.conbeezwei object system.adapter.roadtraffic.0.cputime created

host.conbeezwei object system.adapter.roadtraffic.0.cpu created

host.conbeezwei object system.adapter.roadtraffic.0.compactMode created

host.conbeezwei object system.adapter.roadtraffic.0.connected created

host.conbeezwei object system.adapter.roadtraffic.0.alive created

host.conbeezwei Set default value of roadtraffic.0.info.connection: false

host.conbeezwei object system.adapter.roadtraffic.0 created

Process exited with code 0

**Comment by mcm1957** [comment]
outdated

If problem still exists with 1.x.x please open a new issue
