### ISSUE TITLE
Service kann sich nicht mit Host verbinden?

### ISSUE THREAD

**Issue by hohmannc85** [iobroker-community-adapters/ioBroker.roadtraffic#31]
Hallo, ich habe einen API Key eingegeben, der über die folgende Seite geht
https://geocode.search.hereapi.com/v1/geocode?q=Kirchwalsede-bremen&limit=4&apiKey=KEY.
der service bleibt leider auf rot!
habt ihr einen Tipp?

Pi + iobroker auf dem neusten stand.

**Comment by mcm1957** [comment]
fixed with 1.1.0
